[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "x64_target.json"
# target = "aarch64-unknown-none"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"