# git push --delete origin <tagname>  -- remote
# git tag --delete <tagname>  -- local
  name: build

  on:
    push:
      tags:
        - "v*.*.*"
        - "v*.*.*-*"
        - "v*.*.*-*-*"
        - "pre-release"
        - "beta"
        - "a*.*.*"
        - "latest"
        - "testing"
        - "rc*"
        - "pre-*.*.*"
        - "b*.*.*"
        - "incomplete-*.*.*"

  jobs:
    build:
      name: rust-build
      runs-on: ${{matrix.os}}
      strategy:
        matrix:
          include:
            - build: linux  # build job for x86_64 Linux
              os: ubuntu-latest
              rust: nightly
              target: x86_64-unknown-linux-gnu
              cross: false
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        run: |
          rustup install ${{ matrix.rust }}
          rustup target add ${{ matrix.target }}
          rustup show
      - name: Install rust-src
        run: |
          rustup component add rust-src
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
      - name: Install LLVM tools
        run: rustup component add llvm-tools-preview
      - name: Set Nightly Override
        run: rustup override set nightly
      - name: Install bootimage
        run: |
          cargo install bootimage
      - name: Build
        run: cargo bootimage --release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x64_target/release/bootimage-rsdos.bin
